apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: null
  generation: 4
  labels:
    app: daemon
  name: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: daemon
    spec:
      containers:
      - env:
        - name: DAEMON_TYPE
          value: POD
        - name: HUB_ADDRESS
          value: yourmaster:2600
        - name: POD_NAMESPACE
          value: ose-mon-a
        image: theimage:tag
        imagePullPolicy: Always
        name: daemon
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        purpose: workingnode
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30