apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: deamon
  name: deamon
spec:
  ports:
  - name: 8090-tcp
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: deamon
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}